# pyright: reportUnknownMemberType=false, reportUnknownArgumentType=false, reportDeprecated=false, reportUnusedParameter=false

import json
from datetime import datetime
from typing import Any, Dict, TYPE_CHECKING

import boto3
from boto3.dynamodb.conditions import Key

if TYPE_CHECKING:
    from dataclasses import dataclass

    @dataclass
    class Resources:  # pragma: no cover - used for type checking only
        todos: Any
else:  # pragma: no cover - executed in runtime where module is generated
    from stlv_resources import Resources  # Auto-generated by Stelvio

dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table(Resources.todos.table_name)


def post(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    # Parse the request body
    body = json.loads(event.get("body", "{}"))

    # Create item
    item = {
        "username": body.get("username"),
        "created": datetime.utcnow().isoformat(),
        "title": body.get("title"),
        "done": False,
    }
    # Save to DynamoDB
    table.put_item(Item=item)
    return {"statusCode": 201, "body": json.dumps(item)}


def get(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    # Get username from query parameters
    username = event.get("pathParameters", {}).get("username")

    # Query DynamoDB
    response = table.query(KeyConditionExpression=Key("username").eq(username))

    return {"statusCode": 200, "body": json.dumps({"todos": response["Items"]})}
